import { useEffect, useRef, useState, type CSSProperties } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, AirplaneTilt, MapPin, Sun, Moon, Waves, Check, Plus, X, Phone, FirstAidKit, SuitcaseRolling, ForkKnife, ShoppingBag, Compass, Bed, Bus, Boat, CaretDown, Printer, ListChecks, Info, ArrowLeft, Heart } from '@phosphor-icons/react';
import { days, foodGroups, products, extraProducts, packing, sources, type Day } from './travelData';

const mapLink = (place: string) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place)}`;
const navigation = [['journey', '行程时间线'], ['island', '海岛指南'], ['food', '吃点好的'], ['shopping', '逛购清单'], ['prepare', '出发准备']];
function readSaved(key: string): string[] { try { const v: unknown = JSON.parse(localStorage.getItem(key) || '[]'); return Array.isArray(v) ? v.filter((item): item is string => typeof item === 'string') : []; } catch { return []; } }
function useSavedList(key: string) {
  const [list, setList] = useState<string[]>(() => readSaved(key));
  const [failed, setFailed] = useState(false);
  function toggle(id: string) { const next = list.includes(id) ? list.filter(v => v !== id) : [...list, id]; setList(next); try { localStorage.setItem(key, JSON.stringify(next)); setFailed(false); } catch { setFailed(true); } }
  return { list, toggle, failed };
}
function MapLink({ place, label = '地图' }: { place: string; label?: string }) { return <a className="map-link" href={mapLink(place)} target="_blank" rel="noreferrer"><MapPin size={15} />{label}<ArrowUpRight size={13} /></a>; }
function DayPanel({ day }: { day: Day }) {
  return <article className="day-panel" id={`day-${day.date}`}>
    <div className="day-heading"><div><span className="day-location">{day.en}</span><h3>{day.title}</h3><p>{day.intro}</p></div><span className="day-watermark" aria-hidden="true">{day.date}<small>日</small></span></div>
    <ol className="stops">{day.stops.map((stop, i) => <li key={stop.title}><div className="stop-time"><span className="stop-dot">{i + 1}</span><time>{stop.time}</time></div><div className="stop-body"><div className="stop-title"><h4>{stop.title}</h4>{stop.tag && <span className="tag">{stop.tag}</span>}</div><p>{stop.detail}</p>{stop.place && <MapLink place={stop.place} label="查看地点" />}</div></li>)}</ol>
    <div className="day-sleep"><Bed size={18} /><span>今晚住哪里</span><strong>{day.sleep}</strong></div>
    <p className="day-note"><Info size={17} /><span>{day.note}</span></p>
  </article>;
}

export function App() {
  const [dayIndex, setDayIndex] = useState(0);
  const [showAll, setShowAll] = useState(false);
  const [foodIndex, setFoodIndex] = useState(0);
  const [shopFilter, setShopFilter] = useState('全部');
  const [activeSection, setActiveSection] = useState('journey');
  const [theme, setTheme] = useState(() => { try { return localStorage.getItem('thailand-theme') || (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'); } catch { return 'light'; } });
  const [preview, setPreview] = useState<{ source: string; title: string } | null>(null);
  const packingList = useSavedList('thailand-packing');
  const shoppingList = useSavedList('thailand-shopping');
  const modal = useRef<HTMLDialogElement>(null);
  const lastFocus = useRef<HTMLElement | null>(null);
  useEffect(() => { document.documentElement.dataset.theme = theme; try { localStorage.setItem('thailand-theme', theme); } catch { /* theme still works for this visit */ } }, [theme]);
  useEffect(() => { if (preview) { lastFocus.current = document.activeElement as HTMLElement; modal.current?.showModal(); document.body.style.overflow = 'hidden'; } else { modal.current?.close(); document.body.style.overflow = ''; lastFocus.current?.focus(); } return () => { document.body.style.overflow = ''; }; }, [preview]);
  useEffect(() => { const observer = new IntersectionObserver(entries => { for (const entry of entries) if (entry.isIntersecting) setActiveSection(entry.target.id); }, { rootMargin: '-15% 0px -65% 0px' }); navigation.forEach(([id]) => { const el = document.getElementById(id); if (el) observer.observe(el); }); return () => observer.disconnect(); }, []);
  const filteredProducts = products.filter(p => shopFilter === '全部' || (shopFilter === '我的清单' ? shoppingList.list.includes(p.id) : p.type === shopFilter));
  return <>
    <a className="skip-link" href="#journey">跳到行程</a>
    <header className="site-header"><a className="brand" href="#top"><span className="brand-icon"><AirplaneTilt weight="fill" size={24} /></span><span>去泰国<small>THAILAND, HERE WE GO.</small></span></a><nav aria-label="主导航">{navigation.map(([id, label]) => <a key={id} href={`#${id}`} className={activeSection === id ? 'active' : ''}>{label}</a>)}</nav><div className="header-actions"><button className="icon-button theme-button" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} aria-label={theme === 'light' ? '切换深色模式' : '切换浅色模式'}>{theme === 'light' ? <Moon size={20} /> : <Sun size={20} />}</button><a className="help-link" href="#help"><Phone size={17} /><span>应急联系</span></a></div></header>
    <main id="top">
      <section className="hero" aria-labelledby="hero-title">
        <img className="hero-image" src="/travel/island.webp" alt="海水、白沙与绿色岛屿构成的泰国旅行意境图" width="1536" height="1024" fetchPriority="high" />
        <div className="hero-shade" /><div className="hero-content"><span className="hero-eyebrow">BANGKOK / PATTAYA / KOH LARN</span><h1 id="hero-title">把日子，<br />交给海风。</h1><p>从芭提雅的海，到曼谷的夜。<br />一份属于我们的泰国旅行手册。</p><a className="button hero-button" href="#journey">打开这趟旅程 <ArrowDown size={18} /></a></div>
        <div className="hero-script" aria-hidden="true">Thailand.</div><div className="hero-bottom"><span>4 日出发玩海，8 日带着回忆返程</span><span>慢一点，也没关系。</span></div>
      </section>

      <div className="route-strip content-width" aria-label="旅行路线"><div className="route-intro"><Compass size={22} /><span>这一趟<small>海岛 × 城市</small></span></div><div className="route-place"><small>04 – 06 日</small><strong>芭提雅</strong><span>Pattaya</span></div><span className="route-connector"><Boat size={21} /></span><div className="route-place"><small>05 日往返</small><strong>格兰岛</strong><span>Koh Larn</span></div><span className="route-connector"><Bus size={21} /></span><div className="route-place"><small>06 – 08 日</small><strong>曼谷</strong><span>Bangkok</span></div><div className="route-end"><AirplaneTilt size={24} /><span>满载而归</span></div></div>

      <section id="journey" className="section content-width journey-section">
        <div className="section-heading"><span className="eyebrow">THE ITINERARY</span><h2>每一天，都有好期待。</h2><p>先看路线，再按自己的节奏出发。所有时段均为泰国当地时间。</p></div>
        <div className="arrival-note"><AirplaneTilt size={21} /><div><strong>抵达日，先好好休息</strong><span>入住机场附近酒店，去 7-Eleven 补充用品。月份、抵达日期、航班和酒店待确认。</span></div></div>
        <div className="journey-layout"><aside className="day-sidebar"><div className="day-picker" role="group" aria-label="选择行程日期">{days.map((day, i) => <button key={day.date} aria-pressed={dayIndex === i && !showAll} onClick={() => { setDayIndex(i); setShowAll(false); }} className={dayIndex === i && !showAll ? 'selected' : ''}><span className="date-number">{day.date}<small>日</small></span><span>{day.city}<small>{day.en}</small></span><ArrowUpRight size={19} /></button>)}</div><button className="all-days" onClick={() => setShowAll(!showAll)}><ListChecks size={18} />{showAll ? '收起，按天查看' : '展开完整行程'}<CaretDown className={showAll ? 'rotated' : ''} /></button><div className="sidebar-note"><Sun size={25} /><p>计划留一点空白，<br />惊喜才有地方进来。</p><span>建议时段，可自由调整</span></div></aside><div className={showAll ? 'day-panels all-visible' : 'day-panels'} aria-live="polite">{days.map((day, i) => <div key={day.date} className={showAll || dayIndex === i ? 'day-wrap' : 'day-wrap screen-hidden'}><DayPanel day={day} /></div>)}{!showAll && <div className="day-pagination"><button disabled={dayIndex === 0} onClick={() => setDayIndex(dayIndex - 1)}><ArrowLeft />前一天</button><span>{dayIndex + 1} / {days.length}</span><button disabled={dayIndex === days.length - 1} onClick={() => setDayIndex(dayIndex + 1)}>后一天<ArrowRight /></button></div>}</div></div>
      </section>

      <section id="island" className="island-section section"><div className="content-width island-layout"><div className="island-intro"><span className="eyebrow">A DAY BY THE SEA</span><h2>一座岛，<br />三种看海的心情。</h2><p>5 日留给格兰岛。不必把每一片海滩都打卡，选喜欢的那一片，多待一会儿。</p><div className="ferry-ticket"><Boat size={28} /><div><small>BALI HAI → KOH LARN</small><strong>30 <span>฿ / 人 / 单程</span></strong><p>参考航程 35–45 分钟</p></div><a href={sources.ferry} target="_blank" rel="noreferrer" aria-label="查看轮渡时刻表"><ArrowUpRight size={23} /></a></div><p className="small-note">Tawaen 参考末班 17:00；Nabaan 18:00。<br />建议提前回码头，当天公告优先。</p></div><div className="beach-list">{[
          { n: '01', title: 'Tawaen Beach', mood: '热闹一点', description: '主海滩，水上项目、餐饮和补给集中。适合把上午留给玩水。', place: 'Tawaen Beach Koh Larn', icon: <Waves size={25} /> },
          { n: '02', title: 'Tien Beach', mood: '安静一点', description: '把脚步放慢，拍照、散步、吹海风。从主海滩转乘双条车，现场确认价格。', place: 'Tien Beach Koh Larn', icon: <Sun size={25} /> },
          { n: '03', title: 'Tonglang Beach', mood: '自在一点', description: '原笔记收藏的小众海滩。先确认当天通行条件，再从 Tawaen 一带前往。', place: 'Tonglang Beach Koh Larn', icon: <Heart size={25} /> },
        ].map(b => <article className="beach" key={b.n}><span className="beach-number">{b.n}</span><div><span className="beach-mood">{b.mood}</span><h3>{b.title}</h3><p>{b.description}</p><MapLink place={b.place} label="去这里看海" /></div><span className="beach-icon">{b.icon}</span></article>)}</div></div></section>

      <section id="food" className="section content-width food-section"><div className="section-heading"><h2>旅行的另一半，是好好吃饭。</h2><p>从你的收藏里，整理出三份顺路的美食清单。</p></div><div className="food-layout"><figure className="food-photo"><img src="/travel/food.webp" alt="芒果糯米饭、冬阴功虾汤和泰式奶茶的美食意境图" width="1536" height="1024" loading="lazy" /><figcaption><span>给甜品留个位置</span><strong>芒果糯米饭，<br />当然要再来一份。</strong></figcaption></figure><div className="food-guide"><div className="tab-row" role="group" aria-label="选择美食区域">{foodGroups.map((group, i) => <button className={i === foodIndex ? 'selected' : ''} onClick={() => setFoodIndex(i)} key={group.name} aria-pressed={i === foodIndex}>{group.name}</button>)}</div><p className="food-intro">{foodGroups[foodIndex].intro}</p><div className="restaurants" aria-live="polite">{foodGroups[foodIndex].items.map(([name, description, place], i) => <article key={name}><span className="restaurant-number">{String(i + 1).padStart(2, '0')}</span><div><h3>{name}</h3><p>{description}</p></div>{place ? <a href={mapLink(place)} target="_blank" rel="noreferrer" aria-label={`在地图查找 ${name}`}><ArrowUpRight size={22} /></a> : <span className="pending-label">收藏</span>}</article>)}</div><p className="small-note">店名与菜品来自原笔记；门店位置、营业时间和取号规则请在出发前确认。</p></div></div></section>

      <section id="shopping" className="section shopping-section"><div className="content-width"><div className="section-heading"><span className="eyebrow">A LITTLE SOMETHING TO BRING HOME</span><h2>走进 7-Eleven，照着清单逛。</h2><p>把截图里的小东西整理好了。点一下加入清单，买齐一件，少惦记一件。</p></div><div className="shopping-toolbar"><div className="tab-row" role="group" aria-label="筛选购物清单">{['全部', '护肤彩妆', '日常补给', '我的清单'].map(filter => <button className={shopFilter === filter ? 'selected' : ''} key={filter} aria-pressed={shopFilter === filter} onClick={() => setShopFilter(filter)}>{filter}{filter === '我的清单' && <span className="count">{shoppingList.list.length}</span>}</button>)}</div><span className="save-note"><ShoppingBag size={16} />清单保存在本机</span></div><div className="product-grid" aria-live="polite">{filteredProducts.map(p => <article className="product" key={p.id}><div className="product-image-area"><button className={`product-save ${shoppingList.list.includes(p.id) ? 'saved' : ''}`} onClick={() => shoppingList.toggle(p.id)} aria-pressed={shoppingList.list.includes(p.id)} aria-label={`${shoppingList.list.includes(p.id) ? '移出' : '加入'}清单：${p.name}`}>{shoppingList.list.includes(p.id) ? <Check size={18} /> : <Plus size={18} />}</button><button className="product-preview" onClick={() => setPreview({ source: p.source, title: p.name })} aria-label={`查看原图：${p.name}`}><span className="product-sprite" style={{ '--sprite-x': `${(p.sprite % 3) * 50}%`, '--sprite-y': p.sprite < 3 ? '0%' : '100%' } as CSSProperties} /><span className="view-original">查看原图 <ArrowUpRight size={13} /></span></button></div><div className="product-copy"><span className="product-en">{p.en}</span><h3>{p.name}</h3><p>{p.note}</p><div className="product-price"><strong>{p.price}</strong><span>{p.price === '价格待看' ? '以门店实物为准' : '原笔记参考价'}</span></div></div></article>)}</div>{filteredProducts.length === 0 && <div className="empty-state"><ShoppingBag size={35} /><h3>清单还空着，先挑两件喜欢的。</h3><button className="text-button" onClick={() => setShopFilter('全部')}>看看全部好物 <ArrowRight /></button></div>}{shoppingList.failed && <p role="status">浏览器暂时无法保存，当前清单仅在本次访问有效。</p>}<details className="more-products"><summary>还有这些，也在你的收藏里<span>{extraProducts.length} 组好物 <Plus size={18} /></span></summary><div className="extras-grid">{extraProducts.map(([name, note, source]) => <button key={name} onClick={() => setPreview({ source, title: name })}><span><strong>{name}</strong><small>{note}</small></span><ArrowUpRight size={20} /></button>)}</div></details><p className="shopping-disclaimer">图片为原截图的抠图整理，包装识别请对照原图与实物；价格沿用笔记，不代表当前售价。护肤、洗护与药品仅作收藏清单，不沿用截图中的功效承诺。</p></div></section>

      <section id="prepare" className="section content-width prepare-section"><div className="section-heading"><h2>出发前，把安心装进行李。</h2><p>点选已经准备好的物品。进度会保存在当前浏览器，下次回来继续。</p></div><div className="prepare-grid"><div className="checklist"><div className="checklist-heading"><SuitcaseRolling size={25} /><h3>行前打包清单</h3><span aria-live="polite">{packingList.list.length} / {packing.reduce((n, g) => n + g.items.length, 0)}</span></div>{packing.map(group => <div className="packing-group" key={group.name}><h4>{group.name}</h4><div>{group.items.map(item => <label key={item} className={packingList.list.includes(item) ? 'checked' : ''}><input type="checkbox" checked={packingList.list.includes(item)} onChange={() => packingList.toggle(item)} /><span className="custom-check"><Check size={13} weight="bold" /></span><span>{item}</span></label>)}</div></div>)}{packingList.failed && <p role="status">当前浏览器无法保存进度，请保持此页面打开。</p>}</div><div className="practical"><article className="tdac-note"><span className="tag">入境先准备</span><h3>TDAC，记得填。</h3><p>在抵达日前 3 天内（含抵达日），通过官方页面免费填写。保存确认邮件或 PDF，也可以打印一份备用。</p><a className="text-button" href="https://tdac.immigration.go.th/" target="_blank" rel="noreferrer">前往 TDAC 官方网站 <ArrowUpRight size={18} /></a><small>航班信息、护照与泰国住宿地址提前备好。</small></article><details className="practical-detail" open><summary>手机里的旅行工具 <CaretDown /></summary><dl><div><dt>导航 / 翻译</dt><dd>Google Maps、Google 翻译、豆包</dd></div><div><dt>叫车 / 出行</dt><dd>Bolt、Grab、ViaBus、曼谷地铁通</dd></div><div><dt>预订 / 吃饭</dt><dd>12Go、Booking、大众点评</dd></div><div><dt>兑换现金</dt><dd>SuperRich，先核对门店与当日汇率</dd></div></dl></details><details className="practical-detail"><summary>现金、住宿与未定事项 <CaretDown /></summary><p>原笔记拟带 20,000 ฿ / 人，这里仅作为个人预算记录；入境资金要求请按自己的入境类别查官方说明。</p><p>待补充：出行月份、抵达日期、往返航班与机场、酒店名称地址、返曼谷车票、夜间演出票。</p><p>住宿顺序：抵达日机场周边 → 4、5 日芭提雅 → 6、7 日曼谷。具体入住以预订单为准。</p></details><button className="print-button" onClick={() => window.print()}><Printer size={18} />打印 / 保存行程攻略<ArrowUpRight size={17} /></button></div></div></section>

      <section id="help" className="help-section content-width"><div className="help-heading"><FirstAidKit size={28} /><h2>需要帮助时，先找到这里。</h2><p>泰国当地短号直接拨打；中国手机号漫游无法接通时，请当地人员协助。</p></div><div className="phone-grid"><a href="tel:1155"><span>旅游警察 · 中文服务</span><strong>1155</strong><Phone size={21} /></a><a href="tel:191"><span>泰国报警</span><strong>191</strong><Phone size={21} /></a><a href="tel:1669"><span>医疗急救</span><strong>1669</strong><Phone size={21} /></a><a className="embassy-phone" href="tel:+6622457010"><span>中国驻泰国使馆领保</span><strong>+66 2 245 7010</strong><Phone size={21} /></a></div><div className="help-bottom"><span>外交部全球领保热线 <a href="tel:+861012308">+86 10 12308</a></span><a href={sources.help} target="_blank" rel="noreferrer">官方联系方式 <ArrowUpRight size={14} /></a></div></section>

      <section className="sources-section content-width"><details><summary>关于这份攻略与资料核对 <CaretDown size={16} /></summary><p>行程、餐饮和购物收藏整理自「泰国旅行-资料」中的两份攻略及 11 张图片。日期保留原笔记的 4–8 日，月份未假定；页面中的日内时段是建议安排，不代表预订。</p><p>核对日期：2026 年 9 月 28 日。交通、价格与开放情况可能变化，请以出发日公告为准。</p><div className="source-links"><a href={sources.tdac} target="_blank" rel="noreferrer">TDAC 官方说明 ↗</a><a href={sources.bus} target="_blank" rel="noreferrer">机场大巴运营方 ↗</a><a href={sources.ferry} target="_blank" rel="noreferrer">格兰岛轮渡参考表 ↗</a><a href={sources.palace} target="_blank" rel="noreferrer">大皇宫官网 ↗</a><a href={sources.help} target="_blank" rel="noreferrer">驻泰使馆提醒 ↗</a></div><p>海岛封面、美食照片为 AI 意境配图，不代表景点或商家的现场实拍；商品抠图用于辅助识别，点击可看原始资料。</p></details></section>
    </main>
    <footer className="footer content-width"><a className="footer-brand" href="#top"><AirplaneTilt size={22} weight="fill" />去泰国</a><p>带着期待出发，带着故事回来。</p><a href="#top">回到顶部 <ArrowUpRight size={17} /></a></footer>
    <nav className="mobile-nav" aria-label="手机快捷导航"><a href="#journey"><Compass size={21} /><span>行程</span></a><a href="#food"><ForkKnife size={21} /><span>美食</span></a><a href="#shopping"><ShoppingBag size={21} /><span>逛购</span></a><a href="#prepare"><SuitcaseRolling size={21} /><span>准备</span></a><a href="#help"><Phone size={21} /><span>求助</span></a></nav>
    <dialog ref={modal} className="image-modal" onCancel={() => setPreview(null)} onClick={e => { if (e.target === modal.current) setPreview(null); }} aria-label={preview?.title || '商品原图'}><div className="modal-top"><strong>{preview?.title}</strong><button className="icon-button" autoFocus onClick={() => setPreview(null)} aria-label="关闭原图"><X size={24} /></button></div>{preview && <img src={`/travel/references/${preview.source}.webp`} alt={`${preview.title}的原始收藏截图`} />}</dialog>
  </>;
}
